/**
 * Dynamic Lucide icon renderer for React Native.
 * Maps icon name strings (from the database) to lucide-react-native components.
 * 
 * Usage: <LucideIcon name="scissors" size={16} color="#333" />
 * 
 * If the icon name isn't in the map, falls back to a Star icon.
 */
import React from "react";
import {
  Award,
  Baby,
  Beer,
  Bike,
  Bird,
  BookOpen,
  Briefcase,
  Brush,
  Building2,
  Cake,
  Camera,
  Car,
  Cat,
  Church,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Crown,
  Dog,
  Droplets,
  Dumbbell,
  Fish,
  Flag,
  Flame,
  Flower2,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HeadphonesIcon,
  Heart,
  Home,
  Hotel,
  Leaf,
  MapPin,
  Medal,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Palette,
  PartyPopper,
  PenTool,
  Phone,
  Pill,
  Pizza,
  Plane,
  Rocket,
  Ring,
  Scissors,
  Shield,
  Ship,
  Shirt,
  Sparkles,
  Speaker,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Trees,
  Trophy,
  Truck,
  Tv,
  Users,
  Utensils,
  Warehouse,
  Watch,
  Wine,
  Wrench,
  Zap,
} from "lucide-react-native";
import type { LucideProps } from "lucide-react-native";

// Map of icon name (kebab-case as stored in DB) to component
const ICON_MAP: Record<string, React.FC<LucideProps>> = {
  "award": Award,
  "baby": Baby,
  "beer": Beer,
  "bike": Bike,
  "bird": Bird,
  "book-open": BookOpen,
  "briefcase": Briefcase,
  "brush": Brush,
  "building-2": Building2,
  "cake": Cake,
  "camera": Camera,
  "car": Car,
  "cat": Cat,
  "church": Church,
  "clock": Clock,
  "cloud": Cloud,
  "coffee": Coffee,
  "compass": Compass,
  "crown": Crown,
  "dog": Dog,
  "droplets": Droplets,
  "dumbbell": Dumbbell,
  "fish": Fish,
  "flag": Flag,
  "flame": Flame,
  "flower-2": Flower2,
  "gamepad-2": Gamepad2,
  "gem": Gem,
  "gift": Gift,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "hammer": Hammer,
  "handshake": Handshake,
  "headphones": HeadphonesIcon,
  "heart": Heart,
  "home": Home,
  "hotel": Hotel,
  "leaf": Leaf,
  "map-pin": MapPin,
  "medal": Medal,
  "mic": Mic,
  "monitor": Monitor,
  "moon": Moon,
  "mountain": Mountain,
  "music": Music,
  "palette": Palette,
  "party-popper": PartyPopper,
  "pen-tool": PenTool,
  "phone": Phone,
  "pill": Pill,
  "pizza": Pizza,
  "plane": Plane,
  "ring": Ring,
  "rocket": Rocket,
  "scissors": Scissors,
  "shield": Shield,
  "ship": Ship,
  "shirt": Shirt,
  "sparkles": Sparkles,
  "speaker": Speaker,
  "star": Star,
  "stethoscope": Stethoscope,
  "store": Store,
  "sun": Sun,
  "syringe": Syringe,
  "trees": Trees,
  "trophy": Trophy,
  "truck": Truck,
  "tv": Tv,
  "users": Users,
  "utensils": Utensils,
  "warehouse": Warehouse,
  "watch": Watch,
  "wine": Wine,
  "wrench": Wrench,
  "zap": Zap,
};

interface LucideIconProps {
  name: string;
  size?: number;
  color?: string;
}

export default function LucideIcon({ name, size = 16, color = "#666" }: LucideIconProps) {
  const IconComponent = ICON_MAP[name] || Star;
  return <IconComponent size={size} color={color} />;
}
